name: Build All

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - run: '& msbuild /m /p:Configuration=Release MagPython\MagPython.metaproj'
      - run: 'cd MagPython && ren Release MagPython && 7z a -r ..\MagPython.zip MagPython'
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: build-artifacts
          retention-days: 7
          path: MagPython.zip
